const today = new Date().toISOString().substring(0, 10);

export default [
  {
    id: "235f",
    title: "Walk the dog",
    details: "use the blue leash and take extra poop bags",
    date: today,
    time: "18:00",
    list: "General",
    isImportant: true,
    isCompleted: false,
  },
  {
    id: "236f",
    title: "Go to ikea for a new dinnerware set",
    details: "grey or white set",
    date: "2022-11-02",
    time: "",
    list: "Shopping",
    isImportant: false,
    isCompleted: true,
  },
  {
    id: "237f",
    title: "Take the trash out",
    details: "",
    date: today,
    time: "21:30",
    list: "General",
    isImportant: false,
    isCompleted: false,
  },
  {
    id: "238f",
    title: "Go to the gym",
    details: "",
    date: "2023-02-20",
    time: "19:45",
    list: "Exercise",
    isImportant: false,
    isCompleted: false,
  },
  {
    id: "239f",
    title: "Book plane tickets for the holiday",
    details: "this is important!!",
    date: "2023-11-01",
    time: "08:00",
    list: "Shopping",
    isImportant: true,
    isCompleted: false,
  },
];
